const events = [
  {
    id: 1,
    image: require('../assets/images/data/adam-whitlock-I9j8Rk-JYFM-unsplash.jpg'),
    type: 'SORTIE',
    startTime: '2020/01/21 09:10 PM',
    title: 'Festivale des couleurs',
    location: '8010, Adamavo Market, Lome',
    description: 'Description',
    price: 5000,
  },
  // {
  //   id: 2,
  //   image: require('../assets/images/data/cassie-gallegos-6wCWCPwmRJY-unsplash.jpg'),
  //   type: 'PARTY',
  //   startTime: '23/03/2022 13h00',
  //   title: 'UX Design',
  //   location: '8010, Adamavo Market, Lome',
  //   description: 'Description',
  //   price: 3500,
  // },
  {
    id: 3,
    image: require('../assets/images/data/jakob-owens-qoFQxxuk3QY-unsplash.jpg'),
    type: 'PARTY',
    startTime: '2020/02/21 09:10 PM',
    title: 'UI/UX',
    location: '8010, Adamavo Market, Lome',
    description: 'Description',
    price: 'Free',
  },
  {
    id: 4,
    image: require('../assets/images/data/lee-blanchflower-1dW1vEJLlCQ-unsplash.jpg'),
    type: 'CONCERT',
    startTime: '2020/04/21 09:10 PM',
    title: 'Festivale des couleurs',
    location: '8010, Adamavo Market, Lome',
    description: 'Description',
    price: 1000,
  },
  {
    id: 5,
    image: require('../assets/images/data/med-mhamdi-mH_E0K581Yk-unsplash.jpg'),
    type: 'MUSIC',
    startTime: '2020/06/21 09:10 PM',
    title: 'Festivale des couleurs',
    location: '8010, Adamavo Market, Lome',
    description: 'Description',
    price: 'Free',
  },
  {
    id: 6,
    image: require('../assets/images/data/zachary-kadolph-hwHHq82Enf0-unsplash.jpg'),
    type: 'SPORT',
    startTime: '2020/08/21 09:10 PM',
    title: 'Festivale des couleurs',
    location: '8010, Adamavo Market, Lome',
    description: 'Description',
    price: 'Free',
  },
  {
    id: 7,
    image: require('../assets/images/data/connor-coyne-OgqWLzWRSaI-unsplash.jpg'),
    type: 'SPORT',
    startTime: '2020/10/21 09:10 PM',
    title: 'Festivale des couleurs',
    location: '8010, Adamavo Market, Lome',
    description: 'Description',
    price: 'Free',
  },
];

const region = {
  latitude: 6.160584,
  longitude: 1.31352,
};

export {events, region};
