# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'
inhibit_all_warnings!

target 'Vente' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vente


  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  target 'VenteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
