# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'
inhibit_all_warnings!

target 'Vente' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vente


  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'react-native-get-app-name', :path => '../node_modules/react-native-get-app-name'

  pod 'react-native-version-info', :path => '../node_modules/react-native-version-info'

  pod 'react-native-add-calendar-event', :path => '../node_modules/react-native-add-calendar-event'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'

  target 'VenteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
